### ISSUE TITLE
Not updating lanes

### ISSUE THREAD

**Issue by franciscolourenco** [pauldariye/kanbanize#10]
I've setup the service, the webook is working and payloads are being delivered with status 200. There is nothing on the console though and issues are not being moved around. Any suggestions on how to debug this?

**Comment by dariye** [comment]
hmmmm; I'll try to reproduce this and get back to you sometime this week.

**Comment by franciscolourenco** [comment]
Hi, any updates on this? Thanks!

**Comment by franciscolourenco** [comment]
Sorry, I forgot to set the `status` and `project` description on the labels.
